# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-26 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0003_auto_20180325_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='item',
            name='users',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='alias',
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddField(
            model_name='poke',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokes_given', to='logreg.User'),
        ),
        migrations.AddField(
            model_name='poke',
            name='users',
            field=models.ManyToManyField(related_name='acquired_pokes', to='logreg.User'),
        ),
    ]
