# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-26 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0005_auto_20180326_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poke',
            name='users',
        ),
        migrations.AddField(
            model_name='poke',
            name='recipient',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
